flowchart LR
  Client((Client))
  Employe((Employe))
  Admin((Admin))

  U1[Consulter menus]
  U2[Passer commande]
  U3[Suivre commandes]
  U4[Laisser avis]

  U5[Changer statut commande]
  U6[Traiter kanban]
  U7[Moderer avis]

  U8[Gerer menus]
  U9[Gerer comptes internes]
  U10[Gerer clients]

  Client --> U1
  Client --> U2
  Client --> U3
  Client --> U4

  Employe --> U5
  Employe --> U6
  Employe --> U7

  Admin --> U5
  Admin --> U6
  Admin --> U7
  Admin --> U8
  Admin --> U9
  Admin --> U10
